services:
  _defaults:
    autowire: true
    autoconfigure: true

  Lmc\SpiritWebTwigBundle\Factory\TwigFactory:
    arguments:
      - '@twig'
      - '@twig.loader'
      - '%spirit_web_twig.path%'
      - '%spirit_web_twig.path_alias%'

  Twig\Environment:
    factory: ['@Lmc\SpiritWebTwigBundle\Factory\TwigFactory', 'create']